# Generated by Django 3.2 on 2021-04-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('employee_firstname', models.CharField(blank=True, default='', max_length=100)),
                ('employee_lastname', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
