# Generated by Django 3.2 on 2021-04-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookquistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_selfperception_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
